/**
 * FEED_CONFIG - Centralized list of RSS/Atom feed sources.
 * Each entry requires a name and url. 'starred' is optional.
 */
const FEED_CONFIG = [
    { name: "LW curated", url: "https://www.lesswrong.com/feed.xml?view=curated-rss", tags: ["star"] },
    { name: "LW frontpage", url: "https://www.lesswrong.com/feed.xml?view=frontpage-rss&karmaThreshold=45", tags: ["tech"] },
    { name: "LW all", url: "https://www.lesswrong.com/feed.xml?view=community-rss&karmaThreshold=125", tags: ["tech"] },
    { name: "Lil'Log", url: "https://lilianweng.github.io/index.xml", tags: ["star", "people"] },
    { name: "gwern", url: "https://gwern.substack.com/feed", tags: ["star", "people"] },
    { name: "Off The Convex Path", url: "http://www.offconvex.org/feed.xml", tags: ["star"] },
    { name: "Vicki Boykis", url: "https://vickiboykis.com/index.xml", tags: ["star", "people"] },
    { name: "Sebastian Raschka", url: "https://sebastianraschka.com/rss_feed.xml", tags: ["star", "people"] },
    { name: "Irrational Exuberance", url: "https://lethain.com/feeds.xml", tags: ["star", "people"] },
    { name: "Slava Akhmechet", url: "https://www.spakhm.com/feed.rss", tags: ["star", "people"] },
    { name: "apenwarr", url: "https://apenwarr.ca/log/rss.php", tags: ["star", "people"] },
    { name: "The Oatmeal", url: "https://theoatmeal.com/feed/rss", tags: ["star", "comics"] },
    { name: "Shtetl-Optimized", url: "https://scottaaronson.blog/?feed=rss2", tags: ["star", "people"] },
    { name: "XKCD", url: "https://www.xkcd.com/rss.xml", tags: ["star", "comics"] },
    { name: "EA curated", url: "https://forum.effectivealtruism.org/feed.xml?view=curated-rss", tags: ["star"] },
    { name: "EA frontpage", url: "https://forum.effectivealtruism.org/feed.xml?view=frontpage-rss&karmaThreshold=2", tags: ["tech"] },
    { name: "EA all", url: "https://forum.effectivealtruism.org/feed.xml?view=community-rss&karmaThreshold=200", tags: ["tech"] },
    { name: "Benedict Evans", url: "http://ben-evans.com/benedictevans?format=rss", tags: ["people"] },
    { name: "The Pragmatic Engineer", url: "https://blog.pragmaticengineer.com/rss/", tags: ["people"] },
    { name: "Spotify", url: "https://engineering.atspotify.com/feed", tags: ["companies"] },
    { name: "The Gradient", url: "https://thegradient.pub/rss/", tags: ["tech"] },
    { name: "r/MachineLearning", url: "https://www.reddit.com/r/MachineLearning/.rss", tags: ["tech"] },
    { name: "HN Frontpage", url: "https://hnrss.org/frontpage", tags: ["tech"] },
    { name: "HN newest", url: "https://hnrss.org/newest", tags: ["tech"] },
    { name: "The Verge", url: "https://www.theverge.com/rss/index.xml", tags: ["tech"] },
    { name: "Wired", url: "https://www.wired.com/feed/rss", tags: ["tech"] },
    { name: "TechCrunch", url: "https://techcrunch.com/feed/", tags: ["tech"] },
    { name: "Lobsters", url: "https://lobste.rs/rss", tags: ["tech"] },
    { name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index", tags: ["tech"] },
    { name: "Smashing Mag", url: "https://www.smashingmagazine.com/feed/", tags: ["tech"] },
    // { name: "NY Times", url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", tags: ["news"] },
    // { name: "BBC", url: "http://feeds.bbci.co.uk/news/world/rss.xml", tags: ["news"] },
    // { name: "Guardian", url: "https://www.theguardian.com/world/rss", tags: ["news"] },
    // { name: "Reuters-G", url: "https://news.google.com/rss/search?q=site%3Areuters.com&hl=en-US&gl=US&ceid=US%3Aen", tags: ["news"] },
    // { name: "Aljazeera", url: "https://www.aljazeera.com/xml/rss/all.xml", tags: ["news"] },
    // { name: "Associated Press", url: "https://feedx.net/rss/ap.xml", tags: ["news"] },
    { name: "Antirez", url: "http://antirez.com/rss" },
    { url: "https://anildash.com/feed.xml" },
    { url: "https://aresluna.org/main.rss" },
    { url: "https://beej.us/blog/rss.xml" },
    { url: "https://bernsteinbear.com/feed.xml" },
    { url: "https://blog.jim-nielsen.com/feed.xml" },
    { url: "https://blog.miguelgrinberg.com/feed" },
    { url: "https://blog.pixelmelt.dev/rss/" },
    { url: "https://bogdanthegeek.github.io/blog/index.xml" },
    { url: "https://borretti.me/feed.xml" },
    { url: "https://brutecat.com/rss.xml" },
    { url: "https://buttondown.com/hillelwayne/rss" },
    { url: "https://chadnauseam.com/rss.xml" },
    { url: "https://computer.rip/rss.xml" },
    { url: "https://danielchasehooper.com/feed.xml" },
    { url: "https://danieldelaney.net/feed" },
    { url: "https://danielwirtz.com/rss.xml" },
    { name: "Daring Fireball", url: "https://daringfireball.net/feeds/main", tags: ["tech"] },
    { url: "https://dynomight.net/feed.xml" },
    { url: "https://eli.thegreenplace.net/feeds/all.atom.xml" },
    { url: "https://entropicthoughts.com/feed.xml" },
    { url: "https://ericmigi.com/rss.xml" },
    { url: "https://evanhahn.com/feed.xml" },
    { url: "https://fabiensanglard.net/rss.xml" },
    { url: "https://feed.tedium.co/" },
    { url: "https://geohot.github.io/blog/feed.xml" },
    { url: "https://gilesthomas.com/feed/rss.xml" },
    { url: "https://grantslatton.com/rss.xml" },
    { url: "https://herman.bearblog.dev/feed/" },
    { url: "https://hey.paris/index.xml" },
    { url: "https://hugotunius.se/feed.xml" },
    { url: "https://idiallo.com/feed.rss" },
    { url: "https://it-notes.dragas.net/feed/" },
    { url: "https://jayd.ml/feed.xml" },
    { url: "https://joanwestenberg.com/rss" },
    { url: "https://jyn.dev/atom.xml" },
    { url: "https://keygen.sh/blog/feed.xml" },
    { url: "https://krebsonsecurity.com/feed/" },
    { url: "https://lcamtuf.substack.com/feed" },
    { url: "https://lucumr.pocoo.org/feed.atom" },
    { url: "https://martinalderson.com/feed.xml" },
    { url: "https://matklad.github.io/feed.xml" },
    { url: "https://maurycyz.com/index.xml" },
    { url: "https://micahflee.com/feed/" },
    { url: "https://michael.stapelberg.ch/feed.xml" },
    { url: "https://minimaxir.com/index.xml" },
    { url: "https://mitchellh.com/feed.xml" },
    { url: "https://nesbitt.io/feed.xml" },
    { url: "https://oldvcr.blogspot.com/feeds/posts/default" },
    { url: "https://overreacted.io/rss.xml" },
    { url: "https://philiplaine.com/index.xml" },
    { url: "https://pluralistic.net/feed/" },
    { url: "https://rakhim.exotext.com/rss.xml" },
    { url: "https://refactoringenglish.com/index.xml" },
    { url: "https://shkspr.mobi/blog/feed/" },
    { name: "Simone", url: "https://simone.org/feed/" },
    { url: "https://skyfall.dev/rss.xml" },
    { url: "https://steveblank.com/feed/" },
    { url: "https://susam.net/feed.xml" },
    { url: "https://terriblesoftware.org/feed/" },
    { url: "https://timsh.org/rss/" },
    { url: "https://tomrenner.com/index.xml" },
    { url: "https://worksonmymachine.substack.com/feed" },
    { url: "https://www.abortretry.fail/feed" },
    { url: "https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/feed.xml" },
    { url: "https://www.construction-physics.com/feed" },
    { url: "https://www.downtowndougbrown.com/feed/" },
    { url: "https://www.dwarkeshpatel.com/feed" },
    { url: "https://www.experimental-history.com/feed" },
    { url: "https://www.geoffreylitt.com/feed.xml" },
    { url: "https://www.jeffgeerling.com/blog.xml" },
    { url: "https://www.righto.com/feeds/posts/default" },
    { url: "https://www.seangoedecke.com/rss.xml" },
    { url: "https://www.theatlantic.com/feed/author/derek-thompson/" },
    { url: "https://www.troyhunt.com/rss/" },
    { url: "https://www.wheresyoured.at/rss/" },
    { url: "https://xania.org/feed" },
    { url: "https://xeiaso.net/blog.rss" },
    { name: "Trello", url: "https://trello.engineering/feed.xml", tags: ["companies"] },
    { name: "The Netflix Tech Blog", url: "http://techblog.netflix.com/feeds/posts/default", tags: ["companies"] },
    { name: "Facebook Code", url: "https://code.facebook.com/posts/rss", tags: ["companies"] },
    { name: "Hootsuite", url: "http://code.hootsuite.com/feed/", tags: ["companies"] },
    { name: "XING", url: "https://devblog.xing.com/feed/", tags: ["companies"] },
    { name: "Flipboard", url: "http://engineering.flipboard.com/feed.xml", tags: ["companies"] },
    { name: "Yahoo", url: "http://yahooeng.tumblr.com/rss", tags: ["companies"] },
    { name: "DigitalOcean", url: "https://www.digitalocean.com/community/tutorials/feed", tags: ["companies"] },
    { name: "Intercom", url: "https://engineering.intercom.io/feed.xml", tags: ["companies"] },
    { name: "Songkick", url: "http://devblog.songkick.com/feed/", tags: ["companies"] },
    { name: "ThoughtWorks", url: "https://www.thoughtworks.com/rss/insights.xml", tags: ["companies"] },
    { name: "Squarespace Engineering", url: "http://engineering.squarespace.com/blog?format=RSS", tags: ["companies"] },
    { name: "Airbnb", url: "http://nerds.airbnb.com/feed/", tags: ["companies"] },
    { name: "Stripe", url: "https://stripe.com/blog/feed.rss", tags: ["companies"] },
    { name: "500px", url: "http://developers.500px.com/feed", tags: ["companies"] },
    { name: "Spotify", url: "https://labs.spotify.com/feed/", tags: ["companies"] },
    { name: "Instacart", url: "http://tech.instacart.com/feed/", tags: ["companies"] },
    { name: "LinkedIn", url: "https://engineering.linkedin.com/blog.rss", tags: ["companies"] },
    { name: "Indeed", url: "https://engineering.indeedblog.com/feed/", tags: ["companies"] },
    { name: "Yelp", url: "http://engineeringblog.yelp.com/feed.xml", tags: ["companies"] },
    { name: "Square", url: "http://feeds.feedburner.com/corner-squareup-com", tags: ["companies"] },
    { name: "Ticketmaster", url: "http://tech.ticketmaster.com/feed/", tags: ["companies"] },
    { name: "Flickr", url: "http://code.flickr.net/feed/", tags: ["companies"] },
    { name: "New York Times", url: "http://open.blogs.nytimes.com/feed/", tags: ["companies"] },
    { name: "Imgur", url: "https://blog.imgur.com/feed/", tags: ["companies"] },
    { name: "Pinterest", url: "https://engineering.pinterest.com/blog/rss", tags: ["companies"] },
    { name: "Khan Academy", url: "http://engineering.khanacademy.org/rss.xml", tags: ["companies"] },
    { name: "Kickstarter", url: "https://www.kickstarter.com/backing-and-hacking.atom", tags: ["companies"] },
    { name: "Nextdoor", url: "https://engblog.nextdoor.com/feed/", tags: ["companies"] },
    { name: "Tumblr", url: "http://engineering.tumblr.com/rss", tags: ["companies"] },
    { name: "Bigcommerce", url: "http://www.bigeng.io/rss/", tags: ["companies"] },
    { name: "Gusto", url: "http://engineering.gusto.com/rss/", tags: ["companies"] },
    { name: "Quora", url: "http://engineering.quora.com/rss", tags: ["companies"] },
    { name: "Dropbox", url: "https://blogs.dropbox.com/tech/feed/", tags: ["companies"] },
    { name: "Bazaarvoice", url: "http://blog.developer.bazaarvoice.com/feed/", tags: ["companies"] },
    { name: "Codeship", url: "http://blog.codeship.com/feed/", tags: ["companies"] },
    { name: "Heroku", url: "http://engineering.heroku.com/feed.xml", tags: ["companies"] },
    { name: "Indeed", url: "http://engineering.indeedblog.com/feed/", tags: ["companies"] },
    { name: "Wealthfront", url: "http://eng.wealthfront.com/feed/", tags: ["companies"] },
    { name: "Instagram", url: "http://instagram-engineering.tumblr.com/rss", tags: ["companies"] },
    { name: "GitHub", url: "http://githubengineering.com/atom.xml", tags: ["companies"] },
    { name: "Ebay", url: "http://www.ebaytechblog.com/feed/", tags: ["companies"] },
    { name: "GoSquared", url: "https://engineering.gosquared.com/feed", tags: ["companies"] },
    { name: "Atlassian", url: "https://developer.atlassian.com/blog/feed.xml", tags: ["companies"] },
    { name: "Soundcloud", url: "https://developers.soundcloud.com/blog.rss", tags: ["companies"] },
    { name: "AWS", url: "https://aws.amazon.com/blogs/aws/feed/", tags: ["companies"] },
    { name: "Dailymotion", url: "http://engineering.dailymotion.com/rss/", tags: ["companies"] },
    { name: "Medium", url: "https://medium.com/feed/medium-eng", tags: ["companies"] },
    { name: "Stack Overflow", url: "http://blog.stackoverflow.com/feed/", tags: ["companies"] },
    { name: "Etsy", url: "https://codeascraft.com/feed/", tags: ["companies"] },
    { name: "Twitter", url: "https://blog.twitter.com/api/blog.rss?name=engineering", tags: ["companies"] },
    { name: "Twilio", url: "https://www.twilio.com/engineering/feed/", tags: ["companies"] },
    { name: "Target", url: "https://target.github.io/feed.xml", tags: ["companies"] },
    { name: "Federico Tomassetti", url: "http://tomassetti.me/feed/", tags: ["people"] },
    { name: "Dan Luu", url: "http://danluu.com/atom.xml", tags: ["people"] },
    { name: "Zach Holman", url: "https://zachholman.com/atom.xml", tags: ["people"] },
    { name: "Jon Skeet", url: "http://codeblog.jonskeet.uk/feed/", tags: ["people"] },
    { name: "Geek | Manager", url: "http://feeds.feedburner.com/GeekManager", tags: ["people"] },
    { name: "Martin Fowler", url: "http://www.martinfowler.com/feed.atom", tags: ["people"] },
    { name: "Coding Horror", url: "http://feeds.feedburner.com/codinghorror/", tags: ["people"] },
    { name: "Eleganthack", url: "http://eleganthack.com/feed/", tags: ["people"] },
    { name: "Scott Hanselman", url: "http://feeds.hanselman.com/ScottHanselman", tags: ["people"] },
    { name: "Matt Cutts", url: "https://www.mattcutts.com/blog/feed/", tags: ["people"] },
    { name: "Peter Norvig", url: "http://www.norvig.com/rss-feed.xml", tags: ["people"] },
    { name: "The Clean Code Blog", url: "http://blog.cleancoder.com/atom.xml", tags: ["people"] },
    { name: "Rands in Repose", url: "http://randsinrepose.com/feed/", tags: ["people"] },
    { name: "Cap Watkins", url: "http://capwatkins.com/blog/rss", tags: ["people", "dead"] },
    { name: "Steve Yegge", url: "http://steve-yegge.blogspot.com/feeds/posts/default", tags: ["people"] },
    { name: "Accidentally in Code", url: "http://feeds.feedburner.com/AccidentallyInCode", tags: ["people"] },
    { name: "Elided Branches", url: "http://www.elidedbranches.com/feeds/posts/default", tags: ["people"] },
    { name: "Julia Evans", url: "http://jvns.ca/atom.xml", tags: ["people"] },
    { name: "jbrains.ca", url: "http://blog.jbrains.ca/feed.xml", tags: ["people"] },
    { name: "Joel Spolsky", url: "http://www.joelonsoftware.com/rss.xml", tags: ["people"] },
    { name: "Ethan Mollick", url: "https://www.oneusefulthing.org/feed", tags: ["people", "media"] },
    { name: "LLM Watch", url: "https://www.llmwatch.com/feed", tags: ["media"] },
    { name: "Arg Min", url: "https://www.argmin.net/feed", tags: ["media"] },
    { name: "Lenny's Newsletter", url: "https://www.lennysnewsletter.com/feed", tags: ["media"] },
    { name: "Yannic Kilcher", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew", tags: ["media", "dead"] },
    { name: "Andrej Karpathy", url: "https://karpathy.github.io/feed.xml", tags: ["star", "people"] },
    { name: "Anthropic Blog", url: "https://www.anthropic.com/blog/rss.xml", tags: ["star", "tech", "dead"] },
    { name: "Google DeepMind", url: "https://deepmind.google/blog/rss.xml", tags: ["tech", "companies"] },
    { name: "Simon Willison", url: "https://simonwillison.net/atom/everything/", tags: ["people"] },
    { name: "Astral Codex Ten", url: "https://www.astralcodexten.com/feed", tags: ["star", "people"] },
    { name: "Stratechery", url: "https://stratechery.com/feed/", tags: ["media"] },
    { name: "The Morning Paper", url: "https://blog.acolyer.org/feed/", tags: ["people"] },
    { name: "Ribbonfarm", url: "https://ribbonfarm.com/feed", tags: ["star", "people"] },
    { name: "Meaningness", url: "https://meaningness.substack.com/feed", tags: ["star", "people"] },
    { name: "Melting Asphalt", url: "https://meltingasphalt.com/feed", tags: ["star", "people"] },
    { name: "Embedded in Academia", url: "https://blog.regehr.org/feed", tags: ["people"] },
    { name: "without.boats", url: "https://without.boats/index.xml", tags: ["people"] },
    { name: "Works in Progress", url: "https://www.worksinprogress.news/feed", tags: ["star", "people"] },
    { name: "Roots of Progress", url: "https://rootsofprogress.org/feed", tags: ["star", "people"] },
    { name: "HN Classic", url: "https://hnrss.org/classic", tags: ["tech"] },
    { name: "Interconnects", url: "https://www.interconnects.ai/feed", tags: ["star", "people"] },
    { name: "Freddie deBoer", url: "https://freddiedeboer.substack.com/feed", tags: ["people"] },
    { name: "Today in Tabs", url: "https://rss.beehiiv.com/feeds/ZRiesnGI0u.xml", tags: ["media"] },
    { name: "Adam Jermyn", url: "https://adamjermyn.com/index.xml", tags: ["star", "people"] },
  ];

// Export for different environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = FEED_CONFIG;
} else {
    window.FEED_CONFIG = FEED_CONFIG;
}