/**
 * FEED_CONFIG - Centralized list of RSS/Atom feed sources.
 * Each entry requires a name and url. 'starred' is optional.
 */
const FEED_CONFIG = [
    { url: "https://nitter.net/dieworkwear/rss", tags: ["twitter"]},
    { url: "https://nitter.net/vboykis/rss", tags: ["twitter"]},
    { url: "https://www.lesswrong.com/feed.xml?view=curated-rss", name: "LW curated", tags: ["star"] },
    { url: "https://www.lesswrong.com/feed.xml?view=frontpage-rss&karmaThreshold=45", name: "LW frontpage", tags: ["tech"] },
    { url: "https://www.lesswrong.com/feed.xml?view=community-rss&karmaThreshold=125", name: "LW all", tags: ["tech"] },

    { url: "https://lilianweng.github.io/index.xml", name: "Lil'Log", tags: ["star", "people"] },
    { url: "https://gwern.substack.com/feed", name: "gwern", tags: ["star", "people"] },
    { url: "http://www.offconvex.org/feed.xml", name: "Off The Convex Path", tags: ["star"] },
    { url: "https://vickiboykis.com/index.xml", name: "Vicki Boykis", tags: ["star", "people"] },
    { url: "https://lethain.com/feeds.xml", name: "Irrational Exuberance", tags: ["star", "people"] },
    { url: "https://www.spakhm.com/feed.rss", name: "Slava Akhmechet", tags: ["star", "people"] },
    { url: "https://apenwarr.ca/log/rss.php", name: "apenwarr", tags: ["star", "people"] },
    { url: "https://theoatmeal.com/feed/rss", name: "The Oatmeal", tags: ["star", "comics"] },
    { url: "https://scottaaronson.blog/?feed=rss2", name: "Shtetl-Optimized", tags: ["star", "people"] },
    { url: "https://www.xkcd.com/rss.xml", name: "XKCD", tags: ["star", "comics"] },
    { url: "https://forum.effectivealtruism.org/feed.xml?view=curated-rss", name : "EA curated", tags: ["star"] },
    { url: "https://forum.effectivealtruism.org/feed.xml?view=frontpage-rss&karmaThreshold=2", name : "EA frontpage", tags: ["tech"] },
    { url: "https://forum.effectivealtruism.org/feed.xml?view=community-rss&karmaThreshold=200", name : "EA all", tags: ["tech"] },

    { url: "http://ben-evans.com/benedictevans?format=rss", name:"Benedict Evans"},
    { url: "https://blog.pragmaticengineer.com/rss/", name:"The Pragmatic Engineer"},
    { url: "https://jvns.ca/atom.xml", name: "Julia Evans"},

    { name: "Spotify", url: "https://engineering.atspotify.com/feed", tags: ["companies"] },

    
    // { url: "https://rss.arxiv.org/rss/cs.cl+cs.cv", name: "cs.cl+cs.cv", tags: ["paper"] },
    // { url: "https://rss.arxiv.org/rss/cs.lg", name: "CS.LG", tags: ["paper"] },

    { url: "https://thegradient.pub/rss/", name: "The Gradient", tags: ["tech"]},
    { url: "http://www.reddit.com/r/MachineLearning/.rss", name: "r/MachineLearning", tags: ["tech"]},
    { url: "https://hnrss.org/frontpage", name: "HN Frontpage", tags: ["tech"] },
    { url: "https://hnrss.org/newest", name: "HN newest", tags: ["tech"] },
    { name: "The Verge", url: "https://www.theverge.com/rss/index.xml",  tags: ["tech"] },
    { name: "Wired", url: "https://www.wired.com/feed/rss" ,  tags: ["tech"] },
    { name: "TechCrunch", url: "https://techcrunch.com/feed/",  tags: ["tech"] },
    { name: "Lobsters", url: "https://lobste.rs/rss" ,  tags: ["tech"] },
    { name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index" ,  tags: ["tech"] },
    { name: "Smashing Mag", url: "https://www.smashingmagazine.com/feed/" ,  tags: ["tech"] },

    {url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",  tags: ["news"] },
    {url: "http://feeds.bbci.co.uk/news/world/rss.xml",  tags: ["news"] },
    {url: "https://www.theguardian.com/world/rss",  tags: ["news"] },
    {url: "https://feeds.reuters.com/reuters/topNews",  tags: ["news"] },
    {url: "https://feedx.net/rss/ap.xml",  tags: ["news"] },

    { url: "http://antirez.com/rss", name: "Antirez" },
    { url: "https://anildash.com/feed.xml" },
    { url: "https://aresluna.org/main.rss" },
    { url: "https://beej.us/blog/rss.xml" },
    { url: "https://bernsteinbear.com/feed.xml" },
    { url: "https://blog.jim-nielsen.com/feed.xml" },
    { url: "https://blog.miguelgrinberg.com/feed" },
    { url: "https://blog.pixelmelt.dev/rss/" },
    { url: "https://bogdanthegeek.github.io/blog/index.xml" },
    { url: "https://borretti.me/feed.xml" },
    { url: "https://brutecat.com/rss.xml" },
    { url: "https://buttondown.com/hillelwayne/rss" },
    { url: "https://chadnauseam.com/rss.xml" },
    { url: "https://computer.rip/rss.xml" },
    { url: "https://danielchasehooper.com/feed.xml" },
    { url: "https://danieldelaney.net/feed" },
    { url: "https://danielwirtz.com/rss.xml" },
    { name: "Daring Fireball", url: "https://daringfireball.net/feeds/main" ,  tags: ["tech"] },
    { url: "https://dynomight.net/feed.xml" },
    { url: "https://eli.thegreenplace.net/feeds/all.atom.xml" },
    { url: "https://entropicthoughts.com/feed.xml" },
    { url: "https://ericmigi.com/rss.xml" },
    { url: "https://evanhahn.com/feed.xml" },
    { url: "https://fabiensanglard.net/rss.xml" },
    { url: "https://feed.tedium.co/" },
    { url: "https://geohot.github.io/blog/feed.xml" },
    { url: "https://gilesthomas.com/feed/rss.xml" },
    { url: "https://grantslatton.com/rss.xml" },
    { url: "https://herman.bearblog.dev/feed/" },
    { url: "https://hey.paris/index.xml" },
    { url: "https://hugotunius.se/feed.xml" },
    { url: "https://idiallo.com/feed.rss" },
    { url: "https://it-notes.dragas.net/feed/" },
    { url: "https://jayd.ml/feed.xml" },
    { url: "https://joanwestenberg.com/rss" },
    { url: "https://jyn.dev/atom.xml" },
    { url: "https://keygen.sh/blog/feed.xml" },
    { url: "https://krebsonsecurity.com/feed/" },
    { url: "https://lcamtuf.substack.com/feed" },
    { url: "https://lucumr.pocoo.org/feed.atom" },
    { url: "https://martinalderson.com/feed.xml" },
    { url: "https://matklad.github.io/feed.xml" },
    { url: "https://matuggan.com/rss/" },
    { url: "https://maurycyz.com/index.xml" },
    { url: "https://micahflee.com/feed/" },
    { url: "https://michael.stapelberg.ch/feed.xml" },
    { url: "https://minimaxir.com/index.xml" },
    { url: "https://mitchellh.com/feed.xml" },
    { url: "https://mjg59.dreamwidth.org/data/rss" },
    { url: "https://nesbitt.io/feed.xml" },
    { url: "https://oldvcr.blogspot.com/feeds/posts/default" },
    { url: "https://overreacted.io/rss.xml" },
    { url: "https://philiplaine.com/index.xml" },
    { url: "https://pluralistic.net/feed/" },
    { url: "https://rachelbythebay.com/w/atom.xml" },
    { url: "https://rakhim.exotext.com/rss.xml" },
    { url: "https://refactoringenglish.com/index.xml" },
    { url: "https://shkspr.mobi/blog/feed/" },
    { url: "https://simone.org/feed/", name: "Simone" },
    { url: "https://skyfall.dev/rss.xml" },
    { url: "https://steveblank.com/feed/" },
    { url: "https://susam.net/feed.xml" },
    { url: "https://terriblesoftware.org/feed/" },
    { url: "https://timsh.org/rss/" },
    { url: "https://tomrenner.com/index.xml" },
    { url: "https://utcc.utoronto.ca/~cks/space/blog/?atom" },
    { url: "https://worksonmymachine.substack.com/feed" },
    { url: "https://www.abortretry.fail/feed" },
    { url: "https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/feed.xml" },
    { url: "https://www.construction-physics.com/feed" },
    { url: "https://www.downtowndougbrown.com/feed/" },
    { url: "https://www.dwarkeshpatel.com/feed" },
    { url: "https://www.experimental-history.com/feed" },
    { url: "https://www.geoffreylitt.com/feed.xml" },
    { url: "https://www.jeffgeerling.com/blog.xml" },
    { url: "https://www.righto.com/feeds/posts/default" },
    { url: "https://www.seangoedecke.com/rss.xml" },
    { url: "https://www.tedunangst.com/flak/rss" },
    { url: "https://www.theatlantic.com/feed/author/derek-thompson/" },
    { url: "https://www.troyhunt.com/rss/" },
    { url: "https://www.wheresyoured.at/rss/" },
    { url: "https://xania.org/feed" },
    { url: "https://xeiaso.net/blog.rss" },

  { url: "https://trello.engineering/feed.xml", name: "Trello", tags: ["tech", "companies"] },
  { url: "http://engineering.imvu.com/feed/", name: "IMVU", tags: ["tech", "companies"] },
  { url: "https://developer.zendesk.com/blog.xml", name: "Zendesk", tags: ["tech", "companies"] },
  { url: "http://techblog.netflix.com/feeds/posts/default", name: "The Netflix Tech Blog", tags: ["tech", "companies"] },
  { url: "https://code.facebook.com/posts/rss", name: "Facebook Code", tags: ["tech", "companies"] },
  { url: "https://engineering.groupon.com/feed/", name: "Groupon", tags: ["tech", "companies"] },
  { url: "http://code.hootsuite.com/feed/", name: "Hootsuite", tags: ["tech", "companies"] },
  { url: "http://teespring.engineering/index.xml", name: "Teespring", tags: ["tech", "companies"] },
  { url: "http://tech.gilt.com/rss", name: "Gilt", tags: ["tech", "companies"] },
  { url: "https://devblog.xing.com/feed/", name: "XING", tags: ["tech", "companies"] },
  { url: "http://engineering.flipboard.com/feed.xml", name: "Flipboard", tags: ["tech", "companies"] },
  { url: "http://yahooeng.tumblr.com/rss", name: "Yahoo", tags: ["tech", "companies"] },
  { url: "https://www.digitalocean.com/community/tutorials/feed", name: "DigitalOcean", tags: ["tech", "companies"] },
  { url: "https://techblog.livingsocial.com/atom.xml", name: "LivingSocial", tags: ["tech", "companies"] },
  { url: "http://tech-blog.flipkart.net/feed/", name: "Flipkart", tags: ["tech", "companies"] },
  { url: "http://www.eventbrite.com/engineering/feed/", name: "Eventbrite", tags: ["tech", "companies"] },
  { url: "https://engineering.intercom.io/feed.xml", name: "Intercom", tags: ["tech", "companies"] },
  { url: "http://devblog.songkick.com/feed/", name: "Songkick", tags: ["tech", "companies"] },
  { url: "https://www.thoughtworks.com/rss/insights.xml", name: "ThoughtWorks", tags: ["tech", "companies"] },
  { url: "http://engineering.squarespace.com/blog?format=RSS", name: "Squarespace Engineering", tags: ["tech", "companies"] },
  { url: "http://nerds.airbnb.com/feed/", name: "Airbnb", tags: ["tech", "companies"] },
  { url: "https://stripe.com/blog/feed.rss", name: "Stripe", tags: ["tech", "companies"] },
  { url: "http://allegro.tech/feed.xml", name: "Allegro.tech", tags: ["tech", "companies"] },
  { url: "http://developers.500px.com/feed", name: "500px", tags: ["tech", "companies"] },
  { url: "https://labs.spotify.com/feed/", name: "Spotify", tags: ["tech", "companies"] },
  { url: "http://tech.instacart.com/feed/", name: "Instacart", tags: ["tech", "companies"] },
  { url: "https://engineering.linkedin.com/blog.rss", name: "LinkedIn", tags: ["tech", "companies"] },
  { url: "http://makingvimeo.com/rss", name: "Vimeo", tags: ["tech", "companies"] },
  { url: "http://engineering.indeed.com/feed/", name: "Indeed", tags: ["tech", "companies"] },
  { url: "http://engineeringblog.yelp.com/feed.xml", name: "Yelp", tags: ["tech", "companies"] },
  { url: "http://feeds.feedburner.com/corner-squareup-com", name: "Square", tags: ["tech", "companies"] },
  { url: "http://blog.venmo.com/hf2t3h4x98p5e13z82pl8j66ngcmry?format=RSS", name: "Venmo", tags: ["tech", "companies"] },
  { url: "http://tech.just-eat.com/feed/", name: "Just Eat", tags: ["tech", "companies"] },
  { url: "https://devblog.paypal.com/feed/", name: "Paypal", tags: ["tech", "companies"] },
  { url: "http://tech.ticketmaster.com/feed/", name: "Ticketmaster", tags: ["tech", "companies"] },
  { url: "https://eng.uber.com/feed/", name: "Uber", tags: ["tech", "companies"] },
  { url: "http://code.flickr.net/feed/", name: "Flickr", tags: ["tech", "companies"] },
  { url: "http://open.blogs.nytimes.com/feed/", name: "New York Times", tags: ["tech", "companies"] },
  { url: "https://blog.imgur.com/feed/", name: "Imgur", tags: ["tech", "companies"] },
  { url: "https://engineering.pinterest.com/blog/rss", name: "Pinterest", tags: ["tech", "companies"] },
  { url: "http://engineering.vine.co/rss", name: "Vine", tags: ["tech", "companies"] },
  { url: "http://wongatech.github.io/feed.xml", name: "Wonga Technology", tags: ["tech", "companies"] },
  { url: "http://engineering.khanacademy.org/rss.xml", name: "Khan Academy", tags: ["tech", "companies"] },
  { url: "https://developer.salesforce.com/blogs/engineering/feed", name: "Salesforce", tags: ["tech", "companies"] },
  { url: "https://www.kickstarter.com/backing-and-hacking.atom", name: "Kickstarter", tags: ["tech", "companies"] },
  { url: "http://www.theoculists.com/feed/", name: "Warby Parker", tags: ["tech", "companies"] },
  { url: "https://engblog.nextdoor.com/feed/", name: "Nextdoor", tags: ["tech", "companies"] },
  { url: "http://engineering.tumblr.com/rss", name: "Tumblr", tags: ["tech", "companies"] },
  { url: "http://developers.linecorp.com/blog/?feed=rss2", name: "LINE", tags: ["tech", "companies"] },
  { url: "http://tech.transferwise.com/rss/", name: "Transferwise", tags: ["tech", "companies"] },
  { url: "http://www.eharmony.com/engineering/feed/", name: "Eharmony", tags: ["tech", "companies"] },
  { url: "http://www.bigeng.io/rss/", name: "Bigcommerce", tags: ["tech", "companies"] },
  { url: "http://engineering.tilt.com/atom.xml", name: "Tilt", tags: ["tech", "companies"] },
  { url: "http://engineering.gusto.com/rss/", name: "Gusto", tags: ["tech", "companies"] },
  { url: "http://engineering.quora.com/rss", name: "Quora", tags: ["tech", "companies"] },
  { url: "http://tech.trivago.com/atom.xml", name: "Trivago", tags: ["tech", "companies"] },
  { url: "https://blogs.dropbox.com/tech/feed/", name: "Dropbox", tags: ["tech", "companies"] },
  { url: "http://tech.secretescapes.com/feed/", name: "Secret Escapes", tags: ["tech", "companies"] },
  { url: "http://blog.developer.bazaarvoice.com/feed/", name: "Bazaarvoice", tags: ["tech", "companies"] },
  { url: "https://www.box.com/blog/feed", name: "Box", tags: ["tech", "companies"] },
  { url: "http://blog.codeship.com/feed/", name: "Codeship", tags: ["tech", "companies"] },
  { url: "http://engineering.heroku.com/feed.xml", name: "Heroku", tags: ["tech", "companies"] },
  { url: "http://engineering.skybettingandgaming.com/feed.xml", name: "Sky Betting & Gaming", tags: ["tech", "companies"] },
  { url: "http://engineering.indeedblog.com/feed/", name: "Indeed", tags: ["tech", "companies"] },
  { url: "http://eng.wealthfront.com/feed/", name: "Wealthfront", tags: ["tech", "companies"] },
  { url: "http://instagram-engineering.tumblr.com/rss", name: "Instagram", tags: ["tech", "companies"] },
  { url: "http://githubengineering.com/atom.xml", name: "GitHub", tags: ["tech", "companies"] },
  { url: "http://www.ebaytechblog.com/feed/", name: "Ebay", tags: ["tech", "companies"] },
  { url: "https://engineering.gosquared.com/feed", name: "GoSquared", tags: ["tech", "companies"] },
  { url: "https://developer.atlassian.com/blog/feed.xml", name: "Atlassian", tags: ["tech", "companies"] },
  { url: "http://engineering.foursquare.com/feed/", name: "Foursquare", tags: ["tech", "companies"] },
  { url: "https://developers.soundcloud.com/blog.rss", name: "Soundcloud", tags: ["tech", "companies"] },
  { url: "https://www.periscope.io/blog/atom.xml", name: "Periscope", tags: ["tech", "companies"] },
  { url: "https://aws.amazon.com/blogs/aws/feed/", name: "AWS", tags: ["tech", "companies"] },
  { url: "http://engineering.laterooms.com/rss/", name: "Laterooms", tags: ["tech", "companies"] },
  { url: "http://engineering.dailymotion.com/rss/", name: "Dailymotion", tags: ["tech", "companies"] },
  { url: "https://medium.com/feed/medium-eng", name: "Medium", tags: ["tech", "companies"] },
  { url: "http://engineering.hoteltonight.com/feed.xml", name: "Hoteltonight", tags: ["tech", "companies"] },
  { url: "http://blog.stackoverflow.com/feed/", name: "Stack Overflow", tags: ["tech", "companies"] },
  { url: "http://blog.booking.com/atom.xml", name: "Booking.com", tags: ["tech", "companies"] },
  { url: "https://codeascraft.com/feed/", name: "Etsy", tags: ["tech", "companies"] },
  { url: "https://blog.twitter.com/api/blog.rss?name=engineering", name: "Twitter", tags: ["tech", "companies"] },
  { url: "http://tech.opentable.co.uk/atom.xml", name: "OpenTable UK", tags: ["tech", "companies"] },
  { url: "https://www.twilio.com/engineering/feed/", name: "Twilio", tags: ["tech", "companies"] },
  { url: "https://target.github.io/feed.xml", name: "Target", tags: ["tech", "companies"] },
  { url: "http://tomassetti.me/feed/", name: "Federico Tomassetti", tags: ["tech", "people"] },
  { url: "http://danluu.com/atom.xml", name: "Dan Luu", tags: ["tech", "people"] },
  { url: "https://zachholman.com/atom.xml", name: "Zach Holman", tags: ["tech", "people"] },
  { url: "http://www.billthelizard.com/feeds/posts/default", name: "Bill the Lizard", tags: ["tech", "people"] },
  { url: "http://codeblog.jonskeet.uk/feed/", name: "Jon Skeet", tags: ["tech", "people"] },
  { url: "http://feeds.feedburner.com/GeekManager", name: "Geek | Manager", tags: ["tech", "people"] },
  { url: "http://www.martinfowler.com/feed.atom", name: "Martin Fowler", tags: ["tech", "people"] },
  { url: "http://feeds.feedburner.com/codinghorror/", name: "Coding Horror", tags: ["tech", "people"] },
  { url: "http://eleganthack.com/feed/", name: "Eleganthack", tags: ["tech", "people"] },
  { url: "http://feeds.hanselman.com/ScottHanselman", name: "Scott Hanselman", tags: ["tech", "people"] },
  { url: "https://www.mattcutts.com/blog/feed/", name: "Matt Cutts", tags: ["tech", "people"] },
  { url: "http://www.norvig.com/rss-feed.xml", name: "Peter Norvig", tags: ["tech", "people"] },
  { url: "http://blog.cleancoder.com/atom.xml", name: "The Clean Code Blog", tags: ["tech", "people"] },
  { url: "http://randsinrepose.com/feed/", name: "Rands in Repose", tags: ["tech", "people"] },
  { url: "http://blog.capwatkins.com/feed", name: "Cap Watkins", tags: ["tech", "people"] },
  { url: "http://steve-yegge.blogspot.com/feeds/posts/default", name: "Steve Yegge", tags: ["tech", "people"] },
  { url: "http://feeds.feedburner.com/AccidentallyInCode", name: "Accidentally in Code", tags: ["tech", "people"] },
  { url: "http://www.paperplanes.de/rss.xml", name: "paperplanes", tags: ["tech", "people"] },
  { url: "http://www.elidedbranches.com/feeds/posts/default", name: "Elided Branches", tags: ["tech", "people"] },
  { url: "http://jvns.ca/atom.xml", name: "Julia Evans", tags: ["tech", "people"] },
  { url: "http://blog.jbrains.ca/feed.xml", name: "jbrains.ca", tags: ["tech", "people"] },
  { url: "http://www.joelonsoftware.com/rss.xml", name: "Joel Spolsky", tags: ["tech", "people"] }

];

// Export for different environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = FEED_CONFIG;
} else {
    window.FEED_CONFIG = FEED_CONFIG;
}
