/**
 * FEED_CONFIG - Centralized list of RSS/Atom feed sources.
 * Each entry requires a name and url. 'starred' is optional.
 */
const FEED_CONFIG = [
    { url: "http://lesserwrong.com/feed.xml" , name: "Less Wrong", starred: true},
    { url: "https://hnrss.org/frontpage", name: "HN Frontpage", starred: true},
    { url: "https://gwern.substack.com/feed" ,name: "gwern", starred: true},
    { url: "http://www.offconvex.org/feed.xml", name: "Off The Convex Path", starred: true},
    { url: "https://vickiboykis.com/index.xml", name: "Vicki Boykis", starred: true},

    {url: "https://forum.effectivealtruism.org/feed.xml?view=frontpage-rss&karmaThreshold=2", name : "EA"},
    { url: "https://hnrss.org/newest", name: "HN newest"},
    { url: "https://rss.arxiv.org/rss/cs.lg", name: "CS.LG"},
    { url: "https://rss.arxiv.org/rss/cs.cl+cs.cv", name: "cs.cl+cs.cv"},
    { name: "The Verge", url: "https://www.theverge.com/rss/index.xml" },
    { name: "Wired", url: "https://www.wired.com/feed/rss" },
    { name: "TechCrunch", url: "https://techcrunch.com/feed/" },
    { name: "Lobsters", url: "https://lobste.rs/rss" },
    { name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index" },
    { name: "Smashing Mag", url: "https://www.smashingmagazine.com/feed/" },


    { url: "http://antirez.com/rss", name: "Antirez" },
    { url: "https://anildash.com/feed.xml" },
    { url: "https://aresluna.org/main.rss" },
    { url: "https://beej.us/blog/rss.xml" },
    { url: "https://bernsteinbear.com/feed.xml" },
    { url: "https://berthub.eu/articles/index.xml" },
    { url: "https://blog.jim-nielsen.com/feed.xml" },
    { url: "https://blog.miguelgrinberg.com/feed" },
    { url: "https://blog.pixelmelt.dev/rss/" },
    { url: "https://bogdanthegeek.github.io/blog/index.xml" },
    { url: "https://borretti.me/feed.xml" },
    { url: "https://brutecat.com/rss.xml" },
    { url: "https://buttondown.com/hillelwayne/rss" },
    { url: "https://chadnauseam.com/rss.xml" },
    { url: "https://computer.rip/rss.xml" },
    { url: "https://danielchasehooper.com/feed.xml" },
    { url: "https://danieldelaney.net/feed" },
    { url: "https://danielwirtz.com/rss.xml" },
    { url: "https://daringfireball.net/feeds/main" },
    { url: "https://devblogs.microsoft.com/oldnewthing/feed" },
    { url: "https://dfarq.homeip.net/feed/" },
    { url: "https://dynomight.net/feed.xml" },
    { url: "https://eli.thegreenplace.net/feeds/all.atom.xml" },
    { url: "https://entropicthoughts.com/feed.xml" },
    { url: "https://ericmigi.com/rss.xml" },
    { url: "https://evanhahn.com/feed.xml" },
    { url: "https://fabiensanglard.net/rss.xml" },
    { url: "https://feed.tedium.co/" },
    { url: "https://geohot.github.io/blog/feed.xml" },
    { url: "https://gilesthomas.com/feed/rss.xml" },
    { url: "https://grantslatton.com/rss.xml" },
    { url: "https://herman.bearblog.dev/feed/" },
    { url: "https://hey.paris/index.xml" },
    { url: "https://hugotunius.se/feed.xml" },
    { url: "https://idiallo.com/feed.rss" },
    { url: "https://it-notes.dragas.net/feed/" },
    { url: "https://jayd.ml/feed.xml" },
    { url: "https://joanwestenberg.com/rss" },
    { url: "https://jyn.dev/atom.xml" },
    { url: "https://keygen.sh/blog/feed.xml" },
    { url: "https://krebsonsecurity.com/feed/" },
    { url: "https://lcamtuf.substack.com/feed" },
    { url: "https://lucumr.pocoo.org/feed.atom" },
    { url: "https://martinalderson.com/feed.xml" },
    { url: "https://matklad.github.io/feed.xml" },
    { url: "https://matuggan.com/rss/" },
    { url: "https://maurycyz.com/index.xml" },
    { url: "https://micahflee.com/feed/" },
    { url: "https://michael.stapelberg.ch/feed.xml" },
    { url: "https://minimaxir.com/index.xml" },
    { url: "https://mitchellh.com/feed.xml" },
    { url: "https://mjg59.dreamwidth.org/data/rss" },
    { url: "https://nesbitt.io/feed.xml" },
    { url: "https://oldvcr.blogspot.com/feeds/posts/default" },
    { url: "https://overreacted.io/rss.xml" },
    { url: "https://philiplaine.com/index.xml" },
    { url: "https://pluralistic.net/feed/" },
    { url: "https://rachelbythebay.com/w/atom.xml" },
    { url: "https://rakhim.exotext.com/rss.xml" },
    { url: "https://refactoringenglish.com/index.xml" },
    { url: "https://shkspr.mobi/blog/feed/" },
    { url: "https://simone.org/feed/", name: "Simone" },
    { url: "https://simonwillison.net/atom/everything/", name: "Simon Willison" },
    { url: "https://skyfall.dev/rss.xml" },
    { url: "https://steveblank.com/feed/" },
    { url: "https://susam.net/feed.xml" },
    { url: "https://terriblesoftware.org/feed/" },
    { url: "https://timsh.org/rss/" },
    { url: "https://tomrenner.com/index.xml" },
    { url: "https://utcc.utoronto.ca/~cks/space/blog/?atom" },
    { url: "https://worksonmymachine.substack.com/feed" },
    { url: "https://www.abortretry.fail/feed" },
    { url: "https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/feed.xml" },
    { url: "https://www.construction-physics.com/feed" },
    { url: "https://www.downtowndougbrown.com/feed/" },
    { url: "https://www.dwarkeshpatel.com/feed" },
    { url: "https://www.experimental-history.com/feed" },
    { url: "https://www.filfre.net/feed/" },
    { url: "https://www.geoffreylitt.com/feed.xml" },
    { url: "https://www.jeffgeerling.com/blog.xml" },
    { url: "https://www.johndcook.com/blog/feed/" },
    { url: "https://www.righto.com/feeds/posts/default" },
    { url: "https://www.seangoedecke.com/rss.xml" },
    { url: "https://www.tedunangst.com/flak/rss" },
    { url: "https://www.theatlantic.com/feed/author/derek-thompson/" },
    { url: "https://www.troyhunt.com/rss/" },
    { url: "https://www.wheresyoured.at/rss/" },
    { url: "https://xania.org/feed" },
    { url: "https://xeiaso.net/blog.rss" }
];

// Export for different environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = FEED_CONFIG;
} else {
    window.FEED_CONFIG = FEED_CONFIG;
}
