const EX_DB = [
{ muscle: 'Chest', functional:'Primary', movement: 'Horizontal Press', name: 'BB bench press', reps: '5-8'},
{ muscle: 'Chest', functional:'Primary', movement: 'Horizontal Press', name: 'DB bench press', reps: '5-8'},
{ muscle: 'Chest', functional:'Primary', movement: 'Horizontal Press', name: 'Cable press', reps: '5-8'},
{ muscle: 'Chest', functional:'Secondary1', movement: 'Inclined Press', name: 'DB inclined chest press', reps: '8-12'},
{ muscle: 'Chest', functional:'Secondary1', movement: 'Inclined Press', name: 'BB inclined chest press', reps: '8-12'},
{ muscle: 'Chest', functional:'Isolation1', movement: 'Fly Variations', name: 'Cable Fly', reps: '12-15'},
{ muscle: 'Chest', functional:'Isolation1', movement: 'Fly Variations', name: 'DB fly', reps: '12-15'},
{ muscle: 'Chest', functional:'Isolation1', movement: 'Fly Variations', name: 'EM Fly', reps: '12-15'},
{ muscle: 'Chest', functional:'Isolation2', movement: 'Fly Variations', name: 'Low to high Cable Fly', reps: '12-15'},
{ muscle: 'Back', functional:'Secondary1', movement: 'Horizontal pull', name: 'Iso lateral front lat pull down', reps: '8-12'},
{ muscle: 'Back', functional:'Secondary1', movement: 'Horizontal pull', name: 'Cable Rows', reps: '8-12'},
{ muscle: 'Back', functional:'Secondary2', movement: 'Vertical Pull', name: 'EM lat pull down', reps: '8-12'},
{ muscle: 'Back', functional:'Secondary2', movement: 'Vertical Pull', name: 'Pull Up', reps: '8-10'},
{ muscle: 'Back', functional:'Isolation1', movement: 'Posture', name: 'Wall angels', reps: '15-20'},
{ muscle: 'Shoulder', functional:'Primary', movement: 'Overhead press', name: 'BB Overhead press', reps: '5-8'},
{ muscle: 'Shoulder', functional:'Primary', movement: 'Overhead press', name: 'DB Overhead press', reps: '8-12'},
{ muscle: 'Shoulder', functional:'Primary', movement: 'Overhead press', name: 'EM overhead press', reps: '8-12'},
{ muscle: 'Shoulder', functional:'Isolation1', movement: 'Lateral head isolation', name: 'Lateral raise', reps: '15-20'},
{ muscle: 'Shoulder', functional:'Isolation2', movement: 'Rear head isolation', name: 'rear delt fly', reps: '15-20'},
{ muscle: 'Shoulder', functional:'Isolation2', movement: 'Rear head isolation', name: 'face pull', reps: '15-20'},
{ muscle: 'Shoulder', functional:'Isolation2', movement: 'Rear head isolation', name: 'Reverse pec deck', reps: '15-20'},
{ muscle: 'Biceps', functional:'Primary', movement: 'Main bicep curl', name: 'BB curl wide grip', reps: '5-8'},
{ muscle: 'Biceps', functional:'Primary', movement: 'Main bicep curl', name: 'DB curl', reps: '5-8'},
{ muscle: 'Biceps', functional:'Secondary1', movement: 'Focus on brachialis and bracioradialis', name: 'Hammer curl', reps: '12-15'},
{ muscle: 'Biceps', functional:'Secondary1', movement: 'Focus on brachialis and bracioradialis', name: 'Any curl with pronated grip', reps: '12-15'},
{ muscle: 'Biceps', functional:'Secondary2', movement: 'Target the peak', name: 'Preacher curl', reps: '12-15'},
{ muscle: 'Biceps', functional:'Secondary2', movement: 'Target the peak', name: 'Concentration curl', reps: '12-15'},
{ muscle: 'Triceps', functional:'Isolation1', movement: 'Lateral head isolation', name: 'Cable tricep push down', reps: '12-15'},
{ muscle: 'Triceps', functional:'Isolation2', movement: 'Long head isolation', name: 'Cable overhead extension', reps: '12-15'},
{ muscle: 'Triceps', functional:'Isolation2', movement: 'Long head isolation', name: 'Skull crushers', reps: '12-15'},
{ muscle: 'Triceps', functional:'Isolation2', movement: 'Long head isolation', name: 'DB extension', reps: '12-15'},
{ muscle: 'Quads', functional:'Primary', movement: 'Squat Variations', name: 'Squat', reps: '5-8'},
{ muscle: 'Quads', functional:'Primary', movement: 'Squat Variations', name: 'Front Squat', reps: '5-8'},
{ muscle: 'Quads', functional:'Primary', movement: 'Squat Variations', name: 'Leg Press', reps: '5-8'},
{ muscle: 'Quads', functional:'Primary', movement: 'Squat Variations', name: 'Hack squat', reps: '5-8'},
{ muscle: 'Quads', functional:'Primary', movement: 'Squat Variations', name: 'Goblet Squat', reps: '5-8'},
{ muscle: 'Quads', functional:'Secondary1', movement: 'Posture', name: 'Step-ups', reps: '12-15'},
{ muscle: 'Quads', functional:'Isolation1', movement: 'Femoris focus', name: 'Leg extension', reps: '15-20'},
{ muscle: 'Quads', functional:'Isolation2', movement: 'Adductor focus', name: 'Hip ADduction', reps: '12-15'},
{ muscle: 'Hamstrings', functional:'Primary', movement: 'Hip Hinge', name: 'Romanian deadlift', reps: '5-8'},
{ muscle: 'Hamstrings', functional:'Primary', movement: 'Hip Hinge', name: 'Good mornings', reps: '5-8'},
{ muscle: 'Hamstrings', functional:'Isolation1', movement: 'Curl variations', name: 'Hamstring curl', reps: '12-15'},
{ muscle: 'Glutes', functional:'Primary', movement: 'Compound lift for glutes', name: 'Hip Thrust', reps: '8-12'},
{ muscle: 'Glutes', functional:'Secondary1', movement: 'Lunges ', name: 'Long Step lunges', reps: '12-15'},
{ muscle: 'Glutes', functional:'Isolation1', movement: 'Abductor focus', name: 'Hip ABduction ', reps: '12-15'},
{ muscle: 'Abs', functional:'Primary', movement: 'Crunch Variations', name: 'Cable crunch', reps: '8-12'},
{ muscle: 'Abs', functional:'Primary', movement: 'Crunch Variations', name: 'Machine Crunch', reps: '8-12'},
{ muscle: 'Abs', functional:'Primary', movement: 'Crunch Variations', name: 'Weighted Situps', reps: '8-12'},
{ muscle: 'Abs', functional:'Secondary1', movement: 'Lower abs focus', name: 'Hanging leg raises', reps: '12-15'},
{ muscle: 'Abs', functional:'Secondary1', movement: 'Lower abs focus', name: 'Hanging knee raises', reps: '12-15'},
{ muscle: 'Abs', functional:'Isolation1', movement: 'Oblique', name: 'Russian twist', reps: '12-15'},
{ muscle: 'Abs', functional:'Isolation1', movement: 'Oblique', name: 'Cable twist', reps: '12-15'},
{ muscle: 'Abs', functional:'Isolation1', movement: 'Oblique', name: 'Side Bend', reps: '12-15'},
{ muscle: 'Neck', functional:'Primary', movement: 'All after lying on a horizontal bench', name: 'Neck curl', reps: '20-30'},
{ muscle: 'Neck', functional:'Primary', movement: 'All after lying on a horizontal bench', name: 'Neck Extension', reps: '20-30'},
{ muscle: 'Neck', functional:'Primary', movement: 'All after lying on a horizontal bench', name: 'Neck rotation', reps: '20-30'},
{ muscle: 'Forearms', functional:'Primary', movement: 'Brachioradialis Focus', name: 'Forearm Flexion', reps: '12-15'},
{ muscle: 'Forearms', functional:'Isolation1', movement: 'Extensor focus', name: 'Forearm Extension', reps: '12-15'},
{ muscle: 'Calves', functional:'Primary', movement: 'Calf raise variations', name: 'Standing calf raise', reps: '15-20'},
{ muscle: 'Calves', functional:'Primary', movement: 'Calf raise variations', name: 'Seated calf raises', reps: '15-20'},
{ muscle: 'Calves', functional:'Isolation1', movement: 'Tibialis focus', name: 'Tibialis raises', reps: '12-15'},
{ muscle: 'Calves', functional:'Isolation2', movement: 'Tibialis focus', name: 'Tibialis curl', reps: '12-15'},
    // Add more here following the same structure
];

// Export for different environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = EX_DB;
} else {
    window.EX_DB = EX_DB;
}